version: '2'
services:

  hadoop-master:
    image: '${HADOOP_BASE_IMAGE}-kerberized:${DOCKER_IMAGES_VERSION}'
    ports:
      - '88:88'
      - '88:88/udp'

  presto-master:
    domainname: docker.cluster
    hostname: presto-master
    image: '${HADOOP_BASE_IMAGE}-kerberized:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh singlenode-kerberized run
    networks:
      default:
        aliases:
         - presto-master.docker.cluster
    ports:
      - '7778:7778'

  application-runner:
    image: '${HADOOP_BASE_IMAGE}-kerberized:${DOCKER_IMAGES_VERSION}'
    environment:
      - TEMPTO_PROFILE_CONFIG_FILE=/docker/volumes/conf/tempto/tempto-configuration-for-docker-kerberos.yaml
